### ISSUE TITLE
Capture onboard slicing meta data

### ISSUE THREAD

**Issue by victorevector** [Robo3D/Meta-Reader#3]
Support for capturing onboard slicing meta data

**Comment by victorevector** [comment]
# Update related to QA testing

QA Pass # 15
QA User Victor
QA Date 3/22/2017
QA App Version RoboLCD 1.5.0 MetaReader 1.0.7
QA RoboOS Version 1.3.0-r2.1
QA Octoprint Version 1.3.1-robo
QA Firmware Version r2-1.1.6

## Issue

Inconsistent capture of onboard slicing meta data. Below you will find the stl files i sliced. "Yin_Yang..." is missing layer count. "Razor_Holder" is missing infill, layer height, and layer count. 

[Razor_holder.STL.zip](https://github.com/Robo3D/Meta-Reader/files/863314/Razor_holder.STL.zip)
[Yin_Yang_Tea_candle_holder.STL.zip](https://github.com/Robo3D/Meta-Reader/files/863315/Yin_Yang_Tea_candle_holder.STL.zip)

**Comment by AllenMcAfee** [comment]
I tested the meta reader on 3 R2s and 1 C2 and found an inconsistency between the meta data displayed on the C2 as compared to the R2s.  Each R2 successfully showed the meta data from Simplify3D, while the C2 did not show any meta data.

Meta Reader version: 1.0.7
![img_0220](https://cloud.githubusercontent.com/assets/4200307/26229699/840df4ac-3bf8-11e7-8b7c-5ae97279d14f.JPG)
![Uploading IMG_0221.JPG…]()

**Comment by victorevector** [comment]
@AllenMcAfee Can you upload some of the gcode files in question? It'll aide with the testing process.

**Comment by Ximidar** [comment]
Allen, could you list your exact testing process? I'm wondering how long
you waited from upload, to viewing the meta data. Did you back out and re
look at the meta data? Basically I would like to know how many chances you
gave the meta reader to produce results before it qualifies as a failure

**Comment by AllenMcAfee** [comment]
@Ximidar I am aware of the lag between loading these values, and did check it at least 3 times during a 2 hour print.  My test was as follows:

- [ ] Sliced all files in Simplify
- [ ] Uploaded files via Octoprint Dashboard
- [ ] Started prints via Octoprint dashboard on:
- 3 R2s (2 Production, 1 Prototype)
- 1 C2 (batch 2 rework)
- [ ] _Waited until autolevel was completed_
- [ ] Checked file meta data via LCD screen at start of actual print

**Results**
All R2s showed the correct Meta data for the 2 separate Simplify-sliced GCODE files.
The single C2 that was tested only showed Z offset.

Given the issues with Cura 2.5 we are seeing (missing meta data values in footer of file), I wanted to test the only 3rd party software we are currently using.

**Comment by Ximidar** [comment]
Could you upload the files you used in a zip and post them here?

**Comment by Ximidar** [comment]
the build time failed to populate because when there's only one hour in the build time it changed the meta data
```
;   Build time: 12 hours 10 minutes
;   Build time: 1 hour 24 minutes
```
